export const TASKS_IN_WORK_LOADED = "TASKS_IN_WORK_LOADED";
export const TASKS_IN_WORK_LOADING = "TASKS_IN_WORK_LOADING";
export const TASKS_IN_WORK_ERROR = "TASKS_IN_WORK_ERROR";
export const TASKS_IN_WORK_ADD_PACK = "TASKS_IN_WORK_ADD_PACK";
