// SCREENS
export const SCREENS_GET_USERS = "SCREENS_GET_USERS";
export const SCREENS_GET_SELECTED_USER = "SCREENS_GET_SELECTED_USER";
export const SCREENS_GET_LOADED_PAGE = "SCREENS_GET_LOADED_PAGE";
export const SCREENS_LOADING_SCREENSHOTS_PACK =
  "SCREENS_LOADING_SCREENSHOTS_PACK";
export const SCREENS_ADD_SCREENSHOTS_PACK = "SCREENS_ADD_SCREENSHOTS_PACK";
export const SCREENS_LOADED = "SCREENS_LOADED";
export const SCREENS_ERROR = "SCREENS_ERROR";
export const SCREENS_RESET_DATA = "SCREENS_RESET_DATA";
export const SCREENS_RESET = "SCREENS_RESET";
