// Loader
export const DETAILS_LOADING_START = "DETAILS_LOADING_START";
export const DETAILS_LOADING_END = "DETAILS_LOADING_END";

// List
export const DEVICES_LIST_SUCCESS = "DEVICES_LIST_SUCCESS";
export const DEVICES_LIST_ERROR = "DEVICES_LIST_ERROR";

// Details
export const DETAILS_PROGRAMS_SUCCESS = "DETAILS_PROGRAMS_SUCCESS";
export const DETAILS_PROGRAMS_ERROR = "DETAILS_PROGRAMS_ERROR";
export const DETAILS_SCREENS_SELECT_USER = "DETAILS_SCREENS_SELECT_USER";
export const DETAILS_SCREENS_SUCCESS = "DETAILS_SCREENS_SUCCESS";
export const DETAILS_SCREENS_ERROR = "DETAILS_SCREENS_ERROR";
export const DETAILS_PORTS_SUCCESS = "DETAILS_PORTS_SUCCESS";
export const DETAILS_PORTS_ERROR = "DETAILS_PORTS_ERROR";
export const DETAILS_BROWSER_SUCCESS = "DETAILS_BROWSER_SUCCESS";
export const DETAILS_BROWSER_ERROR = "DETAILS_BROWSER_ERROR";
export const DETAILS_PROCESSES_SUCCESS = "DETAILS_PROCESSES_SUCCESS";
export const DETAILS_PROCESSES_ERROR = "DETAILS_PROCESSES_ERROR";
export const DETAILS_RESPONSIBLE_SUCCESS = "DETAILS_RESPONSIBLE_SUCCESS";
export const DETAILS_RESPONSIBLE_ERROR = "DETAILS_RESPONSIBLE_ERROR";
export const DETAILS_LOGS_SUCCESS = "DETAILS_LOGS_SUCCESS";
export const DETAILS_LOGS_ERROR = "DETAILS_LOGS_ERROR";
export const DETAILS_ENTRY_SUCCESS = "DETAILS_ENTRY_SUCCESS";
export const DETAILS_ENTRY_ERROR = "DETAILS_ENTRY_ERROR";
