export const PROCESSES_LOADING = "PROCESSES_LOADING";
export const PROCESSES_LOADED = "PROCESSES_LOADED";
export const PROCESSES_ERROR = "PROCESSES_ERROR";
export const PROCESSES_ADD_LIST = "PROCESSES_ADD_LIST";
