export const TASKS_COMPLETED_LOADED = "TASKS_COMPLETED_LOADED";
export const TASKS_COMPLETED_LOADING = "TASKS_COMPLETED_LOADING";
export const TASKS_COMPLETED_ERROR = "TASKS_COMPLETED_ERROR";
export const TASKS_COMPLETED_ADD_PACK = "TASKS_COMPLETED_ADD_PACK";
