export const DEVICES_LIST_LOADING = "DEVICES_LIST_LOADING";
export const DEVICES_LIST_LOADED = "DEVICES_LIST_LOADED";
export const DEVICES_LIST_ERROR = "DEVICES_LIST_ERROR";
export const DEVICES_LIST_ADD = "DEVICES_LIST_ADD";
