export const TASKS_CANCELED_LOADED = "TASKS_CANCELED_LOADED";
export const TASKS_CANCELED_LOADING = "TASKS_CANCELED_LOADING";
export const TASKS_CANCELED_ERROR = "TASKS_CANCELED_ERROR";
export const TASKS_CANCELED_ADD_PACK = "TASKS_CANCELED_ADD_PACK";
