// LOADING
export const APP_READY = "APP_READY";

// NAV_BAR
export const NAV_BAR_OPEN = "NAV_BAR_OPEN";
export const NAV_BAR_CLOSED = "NAV_BAR_CLOSED";

// THEME_SITTINGS
export const THEME_SETTINGS_OPEN = "THEME_SETTINGS_OPEN";
export const THEME_SETTINGS_CLOSED = "THEME_SETTINGS_CLOSED";
export const DARK_MODE_CHANGE = "DARK_MODE_CHANGE";
export const SWITCH_THEME = "SWITCH_THEME";
