export const PROGRAMS_LOADING = "PROGRAMS_LOADING";
export const PROGRAMS_LOADED = "PROGRAMS_LOADED";
export const PROGRAMS_ERROR = "PROGRAMS_ERROR";
export const PROGRAMS_ADD_LIST = "PROGRAMS_ADD_LIST";
export const PROGRAMS_RESET = "PROGRAMS_RESET";
