export const TASKS_DEFERRED_LOADED = "TASKS_DEFERRED_LOADED";
export const TASKS_DEFERRED_LOADING = "TASKS_DEFERRED_LOADING";
export const TASKS_DEFERRED_ERROR = "TASKS_DEFERRED_ERROR";
export const TASKS_DEFERRED_ADD_PACK = "TASKS_DEFERRED_ADD_PACK";
